# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 560d39f5a3aea762990739cef4612900f8a5581b60dd78c0b9e732493551dbd6e5b9175ce4a96b3f08b7dd76cf34cd4b86e9e0b7a02bbb6b943106f61ecae937

test:
  secret_key_base: 80b291ebfbf527e0bb238211da6b9a28054a71e45414a7828ad2e6cdf66339da912c18a57276c579bd2e8e1cda8370739c753c0784dfb8ca9cd37bc9679e572a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
